name = "Klondike"
default_targets = ["win64"]
build_directory = "makelove-build"
love_version = "11.5"
icon_file = "icon.ico"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
    "-./readme.md",
    "-./icon.ico",
    "-./makelove.toml",
    "-./atlas_src/*",
]

[archive_files]
"./lib/licenses" = "licenses"
